# Generated by Django 5.0.7 on 2024-07-29 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=25)),
                ('note_desc', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
