# Generated by Django 5.0.7 on 2024-07-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_desc',
            new_name='note_descr',
        ),
        migrations.AlterModelTable(
            name='note',
            table='NOTE',
        ),
    ]
