# Generated by Django 5.0.7 on 2024-07-29 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_note_descr_note_notedescr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime),
        ),
    ]
